server:
  port: 8070

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: http://localhost:8090  # Use a public service for testing
          predicates:
            - Path=/teacher/**  # Adjust path to match the request
